const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {createEnforcerAorService,normalizeAorIds}=require('../services/enforcerAorService');
const tests=[];const test=(name,run)=>tests.push({name,run});
function database(options={}) {
  const state={users:[],mappings:[],queries:[],released:false,destroyed:false,committed:false,rolledBack:false};let snapshot;
  const conn={beginTransaction(cb){snapshot={users:[...state.users],mappings:[...state.mappings]};cb();},commit(cb){if(options.commitError)return cb(new Error('commit failed'));state.committed=true;cb();},rollback(cb){if(options.rollbackError)return cb(new Error('rollback failed'));state.users=snapshot.users;state.mappings=snapshot.mappings;state.rolledBack=true;cb();},release(){state.released=true;},destroy(){state.destroyed=true;},query(sql,values,cb){
    state.queries.push({sql,values});
    if(/SELECT id, barangay_name FROM enforcer_aors/.test(sql))return cb(null,options.invalid?[]:[{id:5,barangay_name:'Bula'},{id:16,barangay_name:'Lagao'},{id:18,barangay_name:'Mabuhay'}].filter(aor=>!sql.includes('IN (')||values.includes(aor.id)));
    if(/SELECT id FROM users/.test(sql))return cb(null,options.duplicate?[{id:99}]:[]);
    if(/INSERT INTO users/.test(sql)){state.users.push(values);return cb(null,{insertId:10});}
    if(/INSERT INTO enforcer_user_aors/.test(sql)){if(options.mappingError)return cb(new Error('mapping failed'));state.mappings.push(values);return cb(null,{insertId:state.mappings.length});}
    if(/SELECT m.user_id/.test(sql))return cb(null,[{user_id:10,aor_id:16,barangay_name:'Lagao'},{user_id:10,aor_id:5,barangay_name:'Bula'}]);
    cb(new Error('Unexpected test query'));
  }};
  return {state,db:{query:conn.query,getConnection(cb){cb(null,conn);}}};
}
const input={full_name:'Fixture',username:'fixture',hashedPassword:'hashed',status:'active',enforcer_aor_ids:[16,5,18]};
test('IDs normalize duplicates without changing first-selected order',()=>assert.deepEqual(normalizeAorIds([16,'5',16,18]),[16,5,18]));
for(const value of [undefined,[],{},'5',[0],[-1],[1.5],['1 OR 1=1'],[4294967296]])test('reject invalid AOR array '+JSON.stringify(value),()=>assert.throws(()=>normalizeAorIds(value)));
test('active AOR catalog is alphabetical and compact',async()=>{const {db,state}=database();const aors=await createEnforcerAorService(db).listAors();assert.equal(aors.length,3);assert.match(state.queries[0].sql,/ORDER BY barangay_name, id/);assert.deepEqual(state.queries[0].values,['active']);});
test('direct creation accepts arbitrary IDs with no team and preserves first selection bridge',async()=>{const {db,state}=database();assert.equal(await createEnforcerAorService(db).createEnforcer(input),10);assert.deepEqual(state.mappings,[[10,16],[10,5],[10,18]]);assert.deepEqual(state.users[0],['Fixture','fixture','hashed','enforcer','enforcer','Lagao','Lagao','active']);assert(state.committed&&state.released);assert(state.queries.every(q=>!q.sql.includes('enforcer_team')));});
test('one AOR is sufficient and duplicates do not insert duplicate mappings',async()=>{const {db,state}=database();await createEnforcerAorService(db).createEnforcer({...input,enforcer_aor_ids:[5,5]});assert.deepEqual(state.mappings,[[10,5]]);});
test('invalid or inactive catalog IDs reject before insertion',async()=>{const {db,state}=database({invalid:true});await assert.rejects(createEnforcerAorService(db).createEnforcer(input),/active AORs/);assert.equal(state.users.length,0);assert(state.rolledBack&&state.released);});
test('duplicate username rejects atomically',async()=>{const {db,state}=database({duplicate:true});await assert.rejects(createEnforcerAorService(db).createEnforcer(input),/Username/);assert.equal(state.users.length,0);});
for(const failure of ['mappingError','commitError'])test(failure+' rolls back new user and all mappings',async()=>{const {db,state}=database({[failure]:true});await assert.rejects(createEnforcerAorService(db).createEnforcer(input));assert.deepEqual(state.users,[]);assert.deepEqual(state.mappings,[]);assert(state.rolledBack&&state.released);});
test('failed rollback destroys rather than releases uncertain transaction',async()=>{const {db,state}=database({mappingError:true,rollbackError:true});await assert.rejects(createEnforcerAorService(db).createEnforcer(input),/mapping failed/);assert(state.destroyed&&!state.released);});
test('account enrichment is one batched query and preserves other roles and legacy fields',async()=>{const {db,state}=database();const accounts=[{id:10,account_source:'mobile',mobile_role:'enforcer'},{id:11,account_source:'mobile',mobile_role:'enforcer',barangay:'Bula',assigned_source_name:'Bula'},{id:12,account_source:'mobile',mobile_role:'citizen',barangay:'Bula',email:'fixture@example.test'},{id:10,account_source:'web',role:'personnel'}];const result=await createEnforcerAorService(db).enrichAccounts(accounts);assert.deepEqual(result[0].enforcer_aors,['Lagao','Bula']);assert.deepEqual(result[0].enforcer_aor_ids,[16,5]);assert.deepEqual(result[1].enforcer_aors,[]);assert.equal(result[1].barangay,'Bula');assert.equal(result[2],accounts[2]);assert.equal(result[3],accounts[3]);assert.equal(state.queries.length,1);});
test('lists without Enforcers need no direct-AOR query',async()=>{const {db,state}=database();await createEnforcerAorService(db).enrichAccounts([{id:1,account_source:'mobile',mobile_role:'citizen'}]);assert.equal(state.queries.length,0);});
test('additive migration seeds exactly 26 unique official barangays with correct FK types',()=>{const sql=fs.readFileSync(path.join(__dirname,'../database/migrations/20261007_enforcer_direct_aors.sql'),'utf8');const names=[...sql.matchAll(/\('([^']+)'\)/g)].map(m=>m[1]);const expected=['Apopong','Baluan','Batomelong','Buayan','Bula','Calumpang','City Heights','Conel','Dadiangas East','Dadiangas North','Dadiangas South','Dadiangas West','Fatima','Katangawan','Labangal','Lagao','Ligaya','Mabuhay','Olympog','San Isidro','San Jose','Siguel','Sinawal','Tambler','Tinagacan','Upper Labay'];assert.deepEqual(names,expected);assert.equal(new Set(names).size,26);assert.equal((sql.match(/CREATE TABLE IF NOT EXISTS/g)||[]).length,2);assert.match(sql,/user_id INT NOT NULL/);assert.match(sql,/aor_id INT UNSIGNED NOT NULL/);assert.match(sql,/UNIQUE KEY uq_enforcer_user_aor \(user_id, aor_id\)/);assert.match(sql,/ON DUPLICATE KEY UPDATE barangay_name = enforcer_aors.barangay_name/);assert.doesNotMatch(sql,/DROP TABLE|DROP DATABASE|CREATE DATABASE|TRUNCATE|LOCK TABLES|GTID|ALTER TABLE|INSERT INTO users|enforcer_team_members/i);});
(async()=>{for(const {name,run}of tests){await run();console.log('PASS '+name);}console.log(`Enforcer AOR service: ${tests.length}/${tests.length} PASS`);})().catch(error=>{console.error(error);process.exitCode=1;});
